asdsadadaadaddad
addd
adadadadadadadaddad 
adadadadadadadaddadaddadad

daddadad
adadadadadadadaddadadadada
dadadadada 

SASAASA
adadadadadadadaddad
fucntion adaddadadadadadada  a dfada da ad adadadadadadadaddadadadadaada
dadadadadada
dadadadadadada
dad
adadadadadadadaddadadadadadada  
addadadada 
adadadadadadadaddadadadadadadadad
adadadadadadadaddadadadadaadaa
dadadadadadadad
adadadadadadadaddadd
adadadadadadadaddadadadada
debuggera
dadadadadadadadadadad\da\dadadadadadadadadadadad
adadadadadadadaddadadadadadadadada
dadad
a
debuggerad
adadadadadadadaddadadadadadadadadda
debuggeradad
adad
adadadadadadadaddadadadadadadadadad
dadadadadadadadadadadadada
d
adada
dadadadadaa
dadadadadd